package com.omneagate.DTO.EnumDTO;

/**
 * Created by user1 on 6/7/15.
 */
public enum KeyBoardEnum {

    AREGISTER, PREFIX, SUFFIX, RCACTIVATIONSUFFIX, CARDTYPE, MOBILE, NOTHING, OPENSTOCK,FINALSTRING, AADHARPREFIX, AADHARMIDDLE, AADDHARSUFFIX, AREG, PHYSICALSTOCK, REMARKS, RCNUMBER, OTPNUMBER, PROXYNAME;
}
