package com.omneagate.DTO.EnumDTO;

/**
 * Service messages Enum values
 */
public enum ServiceListenerType {
    ERROR_MSG, DEVICE_REGISTER, LOGIN_USER, RESEND_OTP, BENEFICIARY_UPDATION, LOGOUT_USER, FPS_DATA, SEND_BILL, FPS_DATA_BILL, FPS_DATA_COMMODITY, FPS_DATA_BENEFICIARY, QR_CODE, OPEN_STOCK, CONFIGURATION,
    UPGRADE_RESPONSE, FPS_INTENT_REQUEST, CHECKVERSION,CLOSE_SALE ,STOCK_ALLOTMENT_DETAILS_REQUEST, UPGRADE_VERSION, DEVICE_STATUS, CARD_REGISTRATION, CARD_OTP, CARD_OTP_REGENERATE, CARD_ACTIVATION,
    UNSCHEDULED_REPORT, RECONCILIATION, RECONCILIATION_STATUS, PROXY_REGISTRATION, BFD_REGISTRATION,MANTRA_DEVICE_DETAILS
}

