package com.omneagate.DTO.EnumDTO;

/**
 * Created by user1 on 29/5/15.
 */
public enum TableNames {
    TABLE_CARDTYPE, TABLE_PRODUCT, TABLE_FPSMIGRATION,TABLE_SMSPROVIDER,TABLE_STOCKADJUSTMENT, TABLE_SPLRULES, TABLE_FPSSTORE, TABLE_PRODUCTGROUP, TABLE_PRICEOVERRIDE, TABLE_ENTITLEMENTMASTER, TABLE_PERSONBASEDRULE, TABLE_REGIONBASEDRULE, TABLE_BENEFICIARY, TABLE_BILL, TABLE_BENEFREGREQ, TABLE_SERVICEPROVIDER, TABLE_USERDETAIL, TABLE_FPSSTOCK, TABLE_FPSSTOCKINWARD,
    TABLE_AADHAARSEEDING, TABLE_FPSSTOCKADVANCE, TABLE_CLOSESALETRANSACTION, TABLE_DELETEDAADHAARSEEDING, TABLE_BIFURCATIONHISTORY , TABLE_PROXYDETAIL, TABLE_BFDDETAIL, TABLE_POSOPERATINGHOURS, TABLE_INSPECTIONCRITERIA, TABLE_FPSALLOTMENTCOMMODITYDETAIL,TABLE_NFSAPOSDATA
}
